### ISSUE TITLE
[FEAT] add social preview image

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/chest-tracker-for-cr#10]
**Is your feature request related to a problem? Please describe.**
Upload an image to customize your repository’s social media preview. (Can be based on our README.md logo)

Images should be at least 640×320px (1280×640px for best display).

**Additional context**
Can also use the attached template below:

![repository-open-graph-template](https://user-images.githubusercontent.com/11405075/197358876-77ce87f6-d469-4759-9f63-3ce11207d4f0.png)

**Comment by pratik2315** [comment]
Hey @AndreVarandas ! I would like to work on this issue (if its still not solved) but can you explain where exactly this image should go in the website/repo?

**Comment by AndreVarandas** [comment]
Hi @pratik2315 thanks for your help. This image can be placed inside the "extra" folder. We will use it for all media not used inside the app.
