### ISSUE TITLE
[FEAT] repo logo

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/chest-tracker-for-cr#11]
**Is your feature request related to a problem? Please describe.**
We need a logo for our repo :) 

Up to you and your imagination. Anything that is related to the context (Clash Royale and chests) is fine!

**Additional context**
Image should have at least 1024px width.

**Comment by pratik2315** [comment]
Hey @AndreVarandas ! Can I work on this issue if its okay with you?

**Comment by AndreVarandas** [comment]
Hi @pratik2315 yes pleas, thank you so much :) Assigning to you!

**Comment by pratik2315** [comment]
For context this is how the 2 logos look:

## **First one:**

![image](https://user-images.githubusercontent.com/77961530/197360800-01dba6b3-ddac-429c-9bdf-2d967762359c.png)

## **Second one:**

![image](https://user-images.githubusercontent.com/77961530/197360828-3b974ab0-724d-4893-8f81-e81b6dff2f5f.png)


I also wanted to confirm if this is what you meant by repository logo? 
Thanks.
