### ISSUE TITLE
[FEAT] custom fonts

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/chest-tracker-for-cr#16]
**Is your feature request related to a problem? Please describe.**
We need to use two custom fonts: Nunito and Supercell's game font.

**Describe the solution you'd like**
- Install the expo package for loading custom fonts [https://docs.expo.dev/versions/latest/sdk/font/#installation](https://docs.expo.dev/versions/latest/sdk/font/#installation)
- Follow the guide at [https://docs.expo.dev/guides/using-custom-fonts/](https://docs.expo.dev/guides/using-custom-fonts/) in order to load the fonts.

**Additional context**
Find the fonts attached below, please also include them in the project inside the `assets/fonts` folder.

[Fonts.zip](https://github.com/AndreVarandas/chest-tracker-for-cr/files/9845230/Fonts.zip)

**Comment by SubinDuresh** [comment]
Hi @AndreVarandas Can I take up this issue? I can add the fonts to the assets and have them successfully loaded into App.tsx for your use.

**Comment by AndreVarandas** [comment]
Hi @SubinDuresh, thank you! Assigning it to you!
